name: hello world
on:
  push:
    path:
      - '!README.md'
      - '!src/**'
      - '**.js'
    branches:
      - 'main'
      - 'staging'
      - '!dev/**'

  pull_request:
    type: [opened, reopened, synchronize, labeled, unlabeled]

  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 0
          labels: "bug"
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
